# Generated by Flutter tooling. Do not edit.

generated_xcode_build_settings_path = File.expand_path(File.join(flutter_application_path, 'ios', 'Flutter', 'Generated.xcconfig'))
unless File.exist?(generated_xcode_build_settings_path)
  raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure \"flutter pub get\" is executed first"
end
flutter_root = nil
File.foreach(generated_xcode_build_settings_path) do |line|
  match = line.match(/FLUTTER_ROOT=(.*)/)
  flutter_root = match[1].strip if match
end
raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run \"flutter pub get\"" unless flutter_root

require File.expand_path(File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper.rb'))

flutter_ios_podfile_setup
flutter_install_all_ios_pods(Dir.pwd)

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
